apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Because Istio sidecar needs to be placed with Prometheus, this needs to be
# some namespace with Istio sidecar enablement.
namespace: monitoring

resources:
  - istio-federation.yaml

patchesStrategicMerge:
  - patch-crb-namespace.yaml
